version: "3.9"

services:
  postgres:
    image: postgres:16
    container_name: for_liquibase
    environment:
      POSTGRES_USER: ${DATASOURCE_USERNAME}
      POSTGRES_PASSWORD: ${DATASOURCE_PASSWORD}
    ports:
      - "5434:5432"